# Generated by Django 4.2.24 on 2025-09-10 04:51

import core_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='App_User',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.basefield')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
            bases=('core_app.basefield',),
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('basefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core_app.basefield')),
                ('user', models.EmailField(max_length=254)),
                ('token', models.CharField(blank=True, max_length=550, null=True)),
                ('expiry_time', models.DateTimeField(default=core_app.models._default_expiry)),
            ],
            bases=('core_app.basefield',),
        ),
    ]
