# Generated by Django 4.2.24 on 2025-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
